function ddot_phi_y = copy_autogen_ddot_phi_y(in1,tau_y,in3,in4)
%COPY_AUTOGEN_DDOT_PHI_Y
%    DDOT_PHI_Y = COPY_AUTOGEN_DDOT_PHI_Y(IN1,TAU_Y,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Sep-2025 01:32:59

F_px = in4(:,1);
F_pz = in4(:,2);
I_S = in3(:,6);
I_Uy = in3(:,2);
b_phi = in3(:,10);
b_theta = in3(:,9);
dot_phi_y = in1(:,3);
dot_theta_y = in1(:,2);
g = in3(:,8);
h_app = in3(:,11);
l_U = in3(:,4);
m_S = in3(:,5);
m_U = in3(:,1);
r_S = in3(:,7);
tau_py = in4(:,3);
th_y = in1(:,1);
t2 = cos(th_y);
t3 = sin(th_y);
t4 = dot_theta_y.^2;
t5 = l_U.^2;
t6 = l_U.^3;
t7 = m_U.^2;
t8 = r_S.^2;
t9 = t2.^2;
t10 = t3.^2;
ddot_phi_y = (I_Uy.*tau_y+F_px.*I_Uy.*r_S-I_Uy.*b_phi.*dot_phi_y+m_U.*t5.*t9.*tau_y+m_U.*t5.*t10.*tau_y+r_S.*t3.^3.*t4.*t6.*t7+F_px.*m_U.*r_S.*t5.*t9+F_px.*m_U.*r_S.*t5.*t10-b_phi.*dot_phi_y.*m_U.*t5.*t9-b_phi.*dot_phi_y.*m_U.*t5.*t10+l_U.*m_U.*r_S.*t2.*tau_y-l_U.*m_U.*r_S.*t2.*tau_py-g.*r_S.*t2.*t3.*t5.*t7+r_S.*t3.*t4.*t6.*t7.*t9-F_px.*h_app.*l_U.*m_U.*r_S.*t9+I_Uy.*l_U.*m_U.*r_S.*t3.*t4+b_theta.*dot_theta_y.*l_U.*m_U.*r_S.*t2+F_pz.*h_app.*l_U.*m_U.*r_S.*t2.*t3)./(I_S.*I_Uy+I_Uy.*m_S.*t8+I_Uy.*m_U.*t8+t5.*t7.*t8.*t10+I_S.*m_U.*t5.*t9+I_S.*m_U.*t5.*t10+m_S.*m_U.*t5.*t8.*t9+m_S.*m_U.*t5.*t8.*t10);
end
