function ddot_theta_x = copy_autogen_ddot_theta_x(in1,tau_x,in3,in4)
%COPY_AUTOGEN_DDOT_THETA_X
%    DDOT_THETA_X = COPY_AUTOGEN_DDOT_THETA_X(IN1,TAU_X,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Sep-2025 01:33:00

F_py = in4(:,1);
F_pz = in4(:,2);
I_S = in3(:,6);
I_Ux = in3(:,3);
b_phi = in3(:,10);
b_theta = in3(:,9);
dot_phi_x = in1(:,3);
dot_theta_x = in1(:,2);
g = in3(:,8);
h_app = in3(:,11);
l_U = in3(:,4);
m_S = in3(:,5);
m_U = in3(:,1);
r_S = in3(:,7);
tau_px = in4(:,3);
th_x = in1(:,1);
t2 = cos(th_x);
t3 = sin(th_x);
t4 = l_U.^2;
t5 = m_U.^2;
t6 = r_S.^2;
t7 = t2.^2;
t8 = t3.^2;
ddot_theta_x = -(I_S.*tau_x-I_S.*tau_px+I_S.*b_theta.*dot_theta_x+m_S.*t6.*tau_x-m_S.*t6.*tau_px+m_U.*t6.*tau_x-m_U.*t6.*tau_px+b_theta.*dot_theta_x.*m_S.*t6+b_theta.*dot_theta_x.*m_U.*t6+F_py.*I_S.*h_app.*t2+F_pz.*I_S.*h_app.*t3-I_S.*g.*l_U.*m_U.*t3+F_py.*h_app.*m_S.*t2.*t6+F_pz.*h_app.*m_S.*t3.*t6+F_py.*h_app.*m_U.*t2.*t6+F_pz.*h_app.*m_U.*t3.*t6-F_py.*l_U.*m_U.*t2.*t6-g.*l_U.*t3.*t5.*t6+l_U.*m_U.*r_S.*t2.*tau_x+dot_theta_x.^2.*t2.*t3.*t4.*t5.*t6-b_phi.*dot_phi_x.*l_U.*m_U.*r_S.*t2-g.*l_U.*m_S.*m_U.*t3.*t6)./(I_S.*I_Ux+I_Ux.*m_S.*t6+I_Ux.*m_U.*t6+t4.*t5.*t6.*t8+I_S.*m_U.*t4.*t7+I_S.*m_U.*t4.*t8+m_S.*m_U.*t4.*t6.*t7+m_S.*m_U.*t4.*t6.*t8);
end
