function M = frontal_Bm_func(theta)
% AUTO-GENERATED by create_CL_functions_from_handlers
% polynomial-mode: evaluate elementwise polynomials
theta_min = -0.261799; theta_max = 0.261799; 
% clamp theta to [theta_min, theta_max]
theta = min(max(theta, theta_min), theta_max);

M = zeros(4,1);
M(1,1) = polyval([0 0 0 0 0], theta);
M(2,1) = polyval([-0.6510913128377358 -2.2356015599848789e-13      1.9099580731430386  7.7350203687408951e-15      3.7203540267129167], theta);
M(3,1) = polyval([0 0 0 0 0], theta);
M(4,1) = polyval([-4.8162067110908211  2.0965227640010691e-12      -32.67537965241106 -7.4063122521561757e-14     -37.348896429364821], theta);
end
