function M = saggital_Bm_func(theta)
% AUTO-GENERATED by create_CL_functions_from_handlers
% polynomial-mode: evaluate elementwise polynomials
theta_min = -0.261799; theta_max = 0.261799; 
% clamp theta to [theta_min, theta_max]
theta = min(max(theta, theta_min), theta_max);

M = zeros(4,1);
M(1,1) = polyval([0 0 0 0 0], theta);
M(2,1) = polyval([-0.68808964601710942 -4.4078854713077829e-13      1.9662207475571276  1.2090424893759709e-14      3.7203540935691874], theta);
M(3,1) = polyval([0 0 0 0 0], theta);
M(4,1) = polyval([-4.5181027059410868  4.4154700349266043e-12     -32.515329589172012 -1.2112638887190696e-13     -36.569255096011794], theta);
end
