function ddot_theta_y = autogen_ddot_theta_y(in1,tau_y,in3)
%AUTOGEN_DDOT_THETA_Y
%    DDOT_THETA_Y = AUTOGEN_DDOT_THETA_Y(IN1,TAU_Y,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Aug-2025 12:20:58

I_S = in3(:,6);
I_Uy = in3(:,2);
b_phi = in3(:,10);
b_theta = in3(:,9);
dot_phi_y = in1(:,3);
dot_theta_y = in1(:,2);
g = in3(:,8);
l_U = in3(:,4);
m_S = in3(:,5);
m_U = in3(:,1);
r_S = in3(:,7);
th_y = in1(:,1);
t2 = cos(th_y);
t3 = sin(th_y);
t4 = l_U.^2;
t5 = m_U.^2;
t6 = r_S.^2;
t7 = t2.^2;
t8 = t3.^2;
ddot_theta_y = -(I_S.*tau_y+I_S.*b_theta.*dot_theta_y+m_S.*t6.*tau_y+m_U.*t6.*tau_y+b_theta.*dot_theta_y.*m_S.*t6+b_theta.*dot_theta_y.*m_U.*t6-I_S.*g.*l_U.*m_U.*t3-g.*l_U.*t3.*t5.*t6+l_U.*m_U.*r_S.*t2.*tau_y+dot_theta_y.^2.*t2.*t3.*t4.*t5.*t6-b_phi.*dot_phi_y.*l_U.*m_U.*r_S.*t2-g.*l_U.*m_S.*m_U.*t3.*t6)./(I_S.*I_Uy+I_Uy.*m_S.*t6+I_Uy.*m_U.*t6+t4.*t5.*t6.*t8+I_S.*m_U.*t4.*t7+I_S.*m_U.*t4.*t8+m_S.*m_U.*t4.*t6.*t7+m_S.*m_U.*t4.*t6.*t8);
end
