function J_bot = calculateJacobian(in1,R,h)
%calculateJacobian
%    J_bot = calculateJacobian(IN1,R,H)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 17:07:23

theta_x = in1(1,:);
theta_y = in1(2,:);
t2 = cos(theta_x);
t3 = cos(theta_y);
t4 = sin(theta_x);
t5 = sin(theta_y);
J_bot = reshape([0.0,-h.*t2.*t3,-h.*t3.*t4,1.0,0.0,0.0,h.*t3,h.*t4.*t5,-h.*t2.*t5,0.0,t2,t4,0.0,-R,0.0,0.0,0.0,0.0,R,0.0,0.0,0.0,0.0,0.0],[6,4]);
end
